//stack
export const MAIN_STACK = 'MAIN_STACK';

//welcome section
export const SPLASH = 'SPLASH';
export const WELCOME = 'WELCOME';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const FORGOT_PASSWORD_EMAIL = 'FORGOT_PASSWORD_EMAIL';
export const FORGOT_PASSWORD_OTP = 'FORGOT_PASSWORD_OTP';
export const FORGOT_PASSWORD_CHANGE = 'FORGOT_PASSWORD_CHANGE';
export const BOTTOM_TAB = 'BOTTOM_TAB';

// user section
export const HOME = 'HOME';
export const WISHLIST = 'WISHLIST';
export const MY_ORDERS = 'MY_ORDERS';
export const PROFILE = 'PROFILE';
export const TRENDING_COURSES = 'TRENDING_COURSES';
export const SUGGESTED_COURSES = 'SUGGESTED_COURSES';
export const TOP_CATEGORY = 'TOP_CATEGORY';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const SUGGESTED_PRODUCTS = 'SUGGESTED_PRODUCTS';
export const CART = 'CART';
export const PROCEED_TO_PAYMENT = 'PROCEED_TO_PAYMENT';
export const START_COURSE = 'START_COURSE';
export const COURSE_LIST = 'COURSE_LIST';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const COURSE_COMPLETED_SCREEN = 'COURSE_COMPLETED_SCREEN';
export const MCQ_SCREEN = 'MCQ_SCREEN';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const COURSE_DETAILS = 'COURSE_DETAILS';
export const AUDIO_PLAYER_SCREEN = 'AUDIO_PLAYER_SCREEN';
export const NO_CONNECTION = 'NO_CONNECTION';
export const ALL_REVIEWS = 'ALL_REVIEWS';
export const SEACRCH_ALL_TYPE = 'SEACRCH_ALL_TYPE';
export const SUPER_ADMIN_COURSES = 'SUPER_ADMIN_COURSES';
export const SEARCH_COURSE_BY_CATEGORY = 'SEARCH_COURSE_BY_CATEGORY';
